nixpkgs = ['python312', 'postgresql']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements-prod.txt']

[start]
cmd = "alembic upgrade head && uvicorn src.dashboard.app:app --host 0.0.0.0 --port $PORT"
