services:
- buildCommand: pip install -r requirements.txt
  envVars:
  - fromDatabase:
      name: postgres
    key: DATABASE_URL
  name: corporate_app-api
  runtime: python
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  type: web
- name: postgres
  plan: starter
  type: pserv
